
batch_size: 32
num_epochs: 200
num_workers: 16
device: "cuda"  # or "cpu"
sample_rate: 44100
# Optimizer parameters
learning_rate: 0.0001
weight_decay: 0.00001

# Model parameters
model_name: "hstasnet"
model_path: "out/models/hstasnet_20250129.pt"
solver_path: "out/solvers/hstasnet_20250129.pkl"
continue_from: "out/models/hstasnet_20250124.pt"
dataset_path: /home/liam/.datasets/musdb18hq_augmented
model_srcs:
  - "bass"
  - "drums"
  - "other"
  - "vocals"
model_args:
  num_sources: 4
  num_channels: 2
  time_win_size: 1024
  time_hop_size: 512
  time_ftr_size: 512
  spec_win_size: 1024
  spec_hop_size: 512
  spec_fft_size: 1024
  rnn_hidden_size: 512
# Other parameters
log_path: "out/logs/hstasnet.log"
test:
  test_every: 5
  test_dir: /home/liam/.datasets/musdb18hq_augmented/test 
  test_tracks:
     - track_000110
     - track_000605                                               
     - track_000402
     - track_001607    
